import { useState, useRef } from "react";

const signs = ["Aries","Taurus","Gemini","Cancer","Leo","Virgo","Libra","Scorpio","Sagittarius","Capricorn","Aquarius","Pisces"];
const planets = ["Sun","Moon","Mercury","Venus","Mars","Jupiter","Saturn","Uranus","Neptune","Pluto","Rising"];
const OUTER = ["Uranus","Neptune","Pluto"];

const generationDates = {
Uranus: { Aries:"2010-2018",Taurus:"2018-2026",Gemini:"1941-1949",Cancer:"1948-1956",Leo:"1955-1962",Virgo:"1961-1969",Libra:"1968-1975",Scorpio:"1974-1981",Sagittarius:"1981-1988",Capricorn:"1988-1996",Aquarius:"1995-2003",Pisces:"2003-2011" },
Neptune: { Aries:"2025-2039",Taurus:"1874-1889",Gemini:"1888-1902",Cancer:"1901-1916",Leo:"1914-1929",Virgo:"1928-1943",Libra:"1942-1957",Scorpio:"1955-1970",Sagittarius:"1970-1984",Capricorn:"1984-1998",Aquarius:"1998-2012",Pisces:"2011-2026" },
Pluto: { Aries:"2068-2097",Taurus:"1851-1884",Gemini:"1882-1914",Cancer:"1912-1939",Leo:"1937-1958",Virgo:"1956-1972",Libra:"1971-1984",Scorpio:"1983-1995",Sagittarius:"1995-2008",Capricorn:"2008-2024",Aquarius:"2023-2043",Pisces:"2043-2068" },
};

const celebrities = [
{ name:"Lady Gaga", sign:"Aries", sun:"Aries", moon:"Scorpio", rising:"Gemini", born:"Mar 28, 1986", emoji:"🎤", fact:"Her Aries Sun drives her fearless reinvention. She does not follow trends -- she creates them and moves on before anyone catches up." },
{ name:"Adele", sign:"Taurus", sun:"Taurus", moon:"Sagittarius", rising:"Sagittarius", born:"May 5, 1988", emoji:"🎵", fact:"Her Taurus Sun gives her that unmistakable groundedness -- her voice feels like it comes from the earth itself." },
{ name:"Kanye West", sign:"Gemini", sun:"Gemini", moon:"Pisces", rising:"Unknown", born:"Jun 8, 1977", emoji:"🎧", fact:"His Gemini Sun is the genius behind his ability to hold contradictions -- visionary and chaotic, brilliant and volatile, all at once." },
{ name:"Ariana Grande", sign:"Cancer", sun:"Cancer", moon:"Libra", rising:"Capricorn", born:"Jun 26, 1993", emoji:"🌙", fact:"Her Cancer Sun is the source of her otherworldly emotional depth -- she channels genuine feeling into every note in a way that bypasses your defenses." },
{ name:"Jennifer Lopez", sign:"Leo", sun:"Leo", moon:"Scorpio", rising:"Sagittarius", born:"Jul 24, 1969", emoji:"👑", fact:"Her Leo Sun is textbook -- she was literally born to perform, and decades in, she is still the most magnetic person in any room she enters." },
{ name:"Beyonce", sign:"Virgo", sun:"Virgo", moon:"Scorpio", rising:"Libra", born:"Sep 4, 1981", emoji:"⭐", fact:"Her Virgo Sun is the secret behind the flawless execution -- she rehearses until excellence becomes effortless." },
{ name:"Kim Kardashian", sign:"Libra", sun:"Libra", moon:"Pisces", rising:"Sagittarius", born:"Oct 21, 1980", emoji:"💄", fact:"Her Libra Sun explains the brand -- beauty, aesthetics, and relatability weaponized into a billion-dollar empire." },
{ name:"Drake", sign:"Scorpio", sun:"Scorpio", moon:"Scorpio", rising:"Unknown", born:"Oct 24, 1986", emoji:"🎤", fact:"Sun AND Moon in Scorpio -- he literally cannot write a surface-level song. Everything comes from the wound, which is why it hits so hard." },
{ name:"Nicki Minaj", sign:"Sagittarius", sun:"Sagittarius", moon:"Virgo", rising:"Unknown", born:"Dec 8, 1982", emoji:"🏹", fact:"Her Sagittarius Sun is pure -- she expanded rap's entire idea of what a female rapper could be, then kept pushing the boundaries further." },
{ name:"LeBron James", sign:"Capricorn", sun:"Capricorn", moon:"Aries", rising:"Unknown", born:"Dec 30, 1984", emoji:"🏀", fact:"His Capricorn Sun built the empire. He did not just play basketball -- he studied power, built an institution, and played the longest game imaginable." },
{ name:"Oprah Winfrey", sign:"Aquarius", sun:"Aquarius", moon:"Sagittarius", rising:"Sagittarius", born:"Jan 29, 1954", emoji:"📺", fact:"Her Aquarius Sun is the source of her revolutionary vision -- she did not just do television, she transformed what television could mean for humanity." },
{ name:"Rihanna", sign:"Pisces", sun:"Pisces", moon:"Aries", rising:"Aries", born:"Feb 20, 1988", emoji:"💎", fact:"Her Pisces Sun gives her that effortless, otherworldly quality -- she moves through the world like she is partly somewhere else, and it is utterly magnetic." },
];

const facts = {
"Scorpio-Venus": ["Venus in Scorpio means love is never casual for you -- you merge completely or not at all, and people can feel that intensity the moment you show interest.","You have an almost psychic ability to sense when someone is being dishonest with you in love. You may not say it immediately, but you never forget it.","Your love language is transformation. You do not just want a partner -- you want someone who challenges you to evolve at the deepest level.","Venus in Scorpio is considered in its detriment, which means love does not come easily or lightly for you. But when it's real, it's the most powerful bond in the zodiac.","The shadow side of this placement is possessiveness. The gift side is that you love with a loyalty and depth most people never experience in a lifetime.","You are deeply attracted to mystery. Someone too available or too easy to read will rarely hold your attention for long.","Heartbreak for you is a full-body experience. You do not just grieve emotionally -- you transform entirely because of it.","You tend to test people -- not consciously, but you create situations that reveal whether someone is truly trustworthy before you fully open up."],
"Libra-Venus": ["Venus in Libra is the planet in its home sign -- meaning love, beauty, and harmony come naturally to you in a way that feels almost effortless to others.","You have an extraordinary eye for aesthetics. Your home, your style, your environment -- everything around you tends to be carefully curated and beautiful.","You are a natural mediator. You can see both sides of any conflict so clearly that people come to you to help them navigate their relationships.","The challenge with this placement is that you sometimes sacrifice your own needs for the sake of keeping the peace -- and then quietly resent it.","Your charm is completely natural and almost impossible to resist. You rarely have to try to make people like you -- they just do.","You need a partner who is your intellectual equal. Stimulating conversation is genuinely part of your love language.","Indecision in relationships is real for you -- not because you do not know what you want, but because you want everything to be perfectly fair before you choose.","You fall in love with potential. You see who someone could be, not just who they are, which can make you stay in situations longer than you should."],
"Taurus-Venus": ["Venus in Taurus is exalted -- this is one of the most powerful placements for love and beauty in the entire zodiac.","You love through your senses. Physical touch, good food, beautiful surroundings, and comfort are not luxuries for you -- they are how you express and receive love.","You are one of the most loyal partners in the zodiac. Once you commit, you commit fully -- and you expect the same in return.","You take your time falling in love, but once you do, it takes an enormous amount for you to walk away. Stability matters more to you than excitement.","You have a gift for creating beauty everywhere you go. People feel nourished just being in your space.","The shadow of this placement is stubbornness. When you decide something, changing your mind can feel physically uncomfortable.","You are deeply sensual and tend to express love through acts of physical care -- cooking for people, touching them, making their environment beautiful.","Money and material security are tied to your sense of self-worth. Learning that your value is not your bank account is often a lifelong lesson."],
"Aries-Venus": ["Venus in Aries means you fall fast, hard, and all at once -- the chase is genuinely exciting for you, and you lose interest when the thrill fades.","You are bold in love. You will make the first move, say what you feel, and pursue what you want without apology.","Independence is non-negotiable in your relationships. A partner who is too clingy or dependent will push you away faster than anything.","You tend to love competitively -- you want a partner who can match your energy, challenge you, and keep you on your toes.","The shadow of this placement is impulsiveness. You can rush into relationships that look exciting and exit just as quickly when reality sets in.","You are attracted to confidence above almost anything else. Insecurity in a partner is genuinely a turnoff for you.","Venus in Aries people often pioneer new relationship structures. You do not do things the traditional way -- you do things your way.","You have a short fuse in love but also a short memory for conflict. You blow up and then you are completely over it."],
"Gemini-Venus": ["Venus in Gemini means you fall in love with minds first. If someone cannot hold a real conversation with you, the attraction fades fast.","You need variety in love -- not necessarily different partners, but variety in how you connect. Routine kills your romantic spirit.","You are one of the most playful and flirtatious Venus placements. You keep relationships light and fun in a way that people find genuinely refreshing.","The challenge is depth. You can talk about everything brilliantly, but going deep emotionally can feel vulnerable in a way that makes you dart away.","Texting and communication are part of your love language. A partner who goes quiet on you will lose your interest quickly.","You are attracted to people who are curious, witty, and constantly learning. Someone settled and rigid in their thinking simply cannot hold you.","Your love life often reads like a great novel -- full of interesting characters, unexpected plot twists, and brilliant dialogue.","You may have had overlapping love interests at different points -- not because you are disloyal, but because your heart genuinely opens in multiple directions."],
"Cancer-Venus": ["Venus in Cancer means home is where your heart lives. Creating a safe, warm, nurturing environment for your partner is how you say I love you most loudly.","You have an extraordinary emotional memory. You remember exactly how someone made you feel years ago -- the good and the painful.","You are deeply intuitive about the people you love. You often sense what they need before they articulate it.","The challenge is that you can be emotionally guarded at first. Your soft interior is protected by a hard shell, and it takes time to feel safe enough to open it.","You need to feel emotionally secure before physical or romantic connection can deepen. Someone who rushes you will lose you entirely.","Your love is deeply maternal or paternal -- you tend to care for and nurture your partners in ways that go far beyond romance.","The people you love rarely doubt that they are loved. You express it constantly and genuinely, and that kind of devotion is rare.","You may romanticize the past in relationships -- idealizing old loves or holding onto connections longer than is healthy."],
"Leo-Venus": ["Venus in Leo loves grandly and dramatically -- you do not do anything halfway, and your partners know they are loved because you make it impossible to miss.","You need to feel celebrated in your relationships. A partner who takes you for granted or forgets to appreciate you openly will slowly break your heart.","You are incredibly generous in love -- with your time, your attention, your resources, and your affection. You give everything.","Loyalty is your highest value. Betrayal from someone you love hits you harder than almost anything else in life.","The shadow of this placement is pride. Apologizing does not come naturally, and sometimes your ego gets in the way of genuine reconciliation.","You love with flair -- grand gestures, thoughtful gifts, dramatic declarations. If your love is not felt, you feel unseen.","Your love life often becomes the stuff of legend. The stories people tell about you and your relationships are genuinely memorable.","You are attracted to people with confidence and presence -- someone who makes you feel like royalty just by being with them."],
"Virgo-Venus": ["Venus in Virgo expresses love through service and devotion -- you show up, you fix things, you pay attention to details that most people miss.","You are attracted to intelligence and competence. Someone who is good at what they do and takes care of their responsibilities is genuinely attractive to you.","The challenge is that you can critique the people you love as a way of caring -- but they do not always experience it that way.","You have impossibly high standards in love, which can leave you single longer than most. You would genuinely rather be alone than settle.","Health and shared routines become part of your love language. Working out together, cooking together -- this is romance for you.","The shadow of this placement is self-criticism. You can internalize relationship problems as evidence of your own inadequacy.","When you commit, you are one of the most dependable partners in the zodiac. You take relationships seriously and follow through on your promises.","You are not naturally demonstrative with affection, but the depth of your devotion is evident in how consistently you show up."],
"Sagittarius-Venus": ["Venus in Sagittarius loves freely and adventurously -- you need a partner who is also your travel companion, your philosophical sparring partner, and your best friend.","You are attracted to people from different backgrounds, cultures, or belief systems. Someone who expands your worldview is deeply appealing.","Freedom in love is non-negotiable. A relationship that feels like a cage -- even a comfortable one -- will eventually push you out the door.","You are one of the most honest Venus placements. Sometimes brutally so. Diplomacy in love is not your strongest suit.","Your enthusiasm in love is infectious. When you are interested in someone, you make them feel like the most exciting person in the world.","The shadow is commitment avoidance. You genuinely love the feeling of potential, which can make the settled reality of long-term love feel anticlimactic.","You fall in love with ideas as much as people. Someone who has a fascinating philosophy on life will captivate you completely.","You tend to be luckier in love the further you travel -- physically, intellectually, or spiritually -- from where you started."],
"Capricorn-Venus": ["Venus in Capricorn takes love seriously. You do not date casually -- you date with intention, assessing long-term compatibility from the very beginning.","You are attracted to people who are ambitious, successful, and self-sufficient. Someone who has built something in their life earns your deep respect.","You express love through acts of reliability -- showing up on time, keeping your word, building a stable life alongside someone. These are your love letters.","The challenge is that you can be emotionally reserved in ways that make partners feel kept at arm's length, even when you are deeply committed.","You may have experienced love as conditional early in life, which created a belief that you have to earn affection. Unlearning this is often a central life theme.","Your love life tends to improve dramatically with age. You become more comfortable with vulnerability as you accumulate trust in yourself.","When you fully commit, you are one of the most reliable and devoted partners in the zodiac. Your love is built to last.","Status and shared ambition can be aphrodisiacs for you. A partner who is going somewhere in life genuinely excites you."],
"Aquarius-Venus": ["Venus in Aquarius needs intellectual freedom in love above all else. A partner who tries to control your thinking or limit your social world will not last.","You are attracted to people who are unusual, unconventional, or ahead of their time. The ordinary rarely captivates you.","Friendship is the foundation of all your romantic relationships. If you cannot be genuine friends first, the romance does not have a real foundation.","You can appear emotionally detached in love -- not because you do not feel deeply, but because you process emotions through your intellect first.","The shadow of this placement is emotional unavailability. You can intellectualize your feelings so thoroughly that you lose touch with them entirely.","You are genuinely ahead of your time in how you approach love. What you normalized years ago, others are only now beginning to discuss.","When you find your person, the connection is electric and deeply intellectual -- a meeting of minds that feels unlike anything either of you has experienced before.","You may thrive in non-traditional relationship structures, or at least need significant independence within traditional ones."],
"Pisces-Venus": ["Venus in Pisces is exalted -- this is considered the highest expression of Venus energy, meaning your capacity for love, empathy, and devotion is almost limitless.","You love unconditionally and sometimes unwisely. Your capacity to see the best in people can lead you to stay in situations that do not serve you.","You are deeply romantic in the old-fashioned, poetic sense -- love for you exists in another dimension, almost sacred and transcendent.","Your empathy in relationships is your greatest gift and your greatest vulnerability. You absorb your partner's feelings as your own.","You have a gift for making people feel deeply seen and understood. People often feel more like themselves around you than anywhere else.","The shadow of this placement is losing yourself completely in a relationship. Maintaining your own identity while loving deeply is the lifelong work.","Spiritual or creative connection is essential in your romantic life. A purely pragmatic relationship will never fully satisfy you.","You are attracted to people who need saving -- not always healthy, but deeply human. Learning to love people who are already whole is often a central growth edge."],
"Aries-Moon": ["Your Moon in Aries means your emotional reactions are immediate and instinctive -- you feel it, you express it, and often you are over it before others have even processed what happened.","You restore yourself through action, not reflection. When you are emotionally activated, you need to move or the energy has nowhere to go.","Emotional independence is a deep need for you. Being told how to feel, or having someone else's emotions poured onto you, is genuinely depleting.","You are emotionally brave in ways others are not. You will have the hard conversation, confront the difficult truth, and say the thing no one else will say.","The shadow of this placement is emotional impulsivity -- saying or doing things in the heat of the moment that you genuinely regret when you cool down.","Your inner child is a warrior. At your core, you need to feel like you can handle anything -- and you almost always can.","You are most emotionally healthy when you have something to fight for -- a goal, a project, a cause that gives your fire somewhere to go.","People with Moon in Aries often had to learn emotional self-sufficiency early. You did not always feel you had permission to be vulnerable."],
"Cancer-Moon": ["Moon in Cancer is the Moon in its home sign -- giving you one of the most emotionally intuitive, sensitive, and deeply feeling natures in the zodiac.","Your emotional memory is extraordinary. You carry the feeling of every significant moment with you indefinitely -- the joy, the grief, and everything in between.","You often absorb the emotional atmosphere of the room you walk into before you have consciously registered it. You feel it in your body first.","Home is not just a place for you -- it is an emotional state. When your home environment is chaotic or unwelcoming, your entire inner world destabilizes.","The shadow of this placement is emotional manipulation through guilt, or withdrawing into your shell when hurt rather than expressing what is wrong.","You have a gift for nurturing that is almost instinctive. People around you feel fed, held, and cared for -- even when you are not consciously doing anything.","Your intuition about people's emotional states borders on psychic. You often know what someone is feeling before they know it themselves.","The Moon changes signs every 2.5 days, so your emotional rhythms track closely with the lunar cycle. New and full moons hit you with particular intensity."],
"Scorpio-Moon": ["Moon in Scorpio is one of the most emotionally intense placements in the zodiac. Your feelings do not visit -- they take up residence.","You have an instinctive ability to see beneath the surface of people and situations. Pretense does not fool you for long, and dishonesty feels like a physical offense.","You restore through depth -- intense conversations, transformative experiences, or time alone processing the layers of what you have felt.","The shadow of this placement is emotional control as self-protection. If you control what people know about you, they cannot use it against you. Letting that wall down is the work.","You have an extraordinary capacity for loyalty. When you are fully committed to someone, you would walk through fire for them without thinking twice.","Betrayal hits you at a cellular level. You may forgive eventually, but you never fully forget -- and your trust, once broken, is extraordinarily difficult to rebuild.","Your emotional depth means you feel joy, love, and connection more profoundly than most people -- not just pain. The intensity goes in every direction.","Transformation is your emotional cycle. You do not just grow -- you periodically shed an old version of yourself entirely and emerge completely different."],
"Leo-Moon": ["Moon in Leo means your emotional world is dramatic, generous, and deeply expressive. You feel things with your whole chest and you need to express them just as fully.","You restore through creativity, play, and being genuinely celebrated. Feeling unseen or unappreciated is one of the most destabilizing things for your emotional health.","You have a gift for making emotional experiences feel significant and memorable. People feel like their feelings matter more when they share them with you.","Your inner child needs to be the star sometimes -- not out of ego, but because you have a pure, genuine need to be loved for exactly who you are.","The shadow of this placement is emotional pride -- difficulty admitting when you are wrong or when you are hurting, because vulnerability can feel like losing your crown.","You are an extraordinarily loyal emotional support for the people you love. You show up, you cheer loudly, and you defend fiercely.","Dramatic emotional expression comes naturally to you, which can read as intense to more subdued Moon signs -- but for you, it is simply authentic.","When your need for appreciation goes unmet, it can tip into attention-seeking behavior that you later regret. Knowing this pattern is half the work."],
"Aquarius-Moon": ["Moon in Aquarius means you process emotions intellectually -- feelings arrive as ideas first, which means you can articulate them brilliantly but sometimes struggle to actually feel them.","You restore through solitude, intellectual stimulation, and connection to causes larger than yourself. Being around too many people for too long is genuinely draining.","You have an unusual emotional independence that others often mistake for coldness. You simply do not need external validation to know how you feel.","The shadow of this placement is emotional detachment -- intellectualizing your feelings so completely that you lose touch with the actual experience underneath.","You feel things about humanity collectively in a way that is profound and sometimes overwhelming. World events hit you emotionally in a way that surprises more personally-focused signs.","You need significant space in your emotional relationships -- not because you do not care, but because you genuinely require room to be yourself fully.","You are often ahead of your time emotionally. You have processed things, normalized things, and moved through emotional territory that others will not arrive at for years.","When you do connect deeply with someone, it is a meeting of minds and souls that feels genuinely rare -- because for you, it is."],
"Pisces-Moon": ["Moon in Pisces is one of the most psychically sensitive placements in astrology. You pick up on emotional undercurrents in a room before anyone has spoken a word.","You restore through creative expression, spiritual practice, time near water, and genuine solitude where you can decompress from absorbing everyone else's emotions all day.","You have the most empathetic emotional nature in the zodiac. The line between your feelings and other people's feelings is genuinely blurry -- which is both a gift and an enormous burden.","The shadow of this placement is emotional escapism -- retreating into fantasy, sleep, or any numbing behavior when reality feels too heavy.","You often know things emotionally before you have any logical reason to know them. Your gut feelings are frequently more accurate than other people's careful analysis.","You carry other people's pain as your own without realizing it. Regular emotional clearing practices are not optional for you -- they are necessary.","Your emotional world is rich, complex, and layered in ways that are genuinely difficult to articulate. Sometimes you feel things there are simply no words for.","You are at your most emotionally healthy when you have a creative or spiritual outlet for the depth of what you feel. Without that channel, the feelings can become overwhelming."],
"Leo-Sun": ["Your Sun in Leo is ruled by the Sun itself -- the only sign with this distinction -- meaning your identity, your self-expression, and your vitality are inextricably linked.","You were born to shine. Not in a performative way -- in a genuinely luminous way. When you are fully yourself, you light up rooms without trying.","The shadow of this placement is ego fragility beneath the confidence. The roar of the lion can sometimes be loudest when the lion is actually afraid.","You have a gift for making people feel special. When you give someone your full attention, they feel like the only person in the world.","Your creative impulse is central to your identity. Whether it manifests as art, performance, leadership, or simply the way you present yourself -- you are always creating.","You need to be appreciated, and there is nothing shameful about that. The shadow version of this need becomes attention-seeking. The high version becomes true generosity and inspiration.","Loyalty is one of your most defining qualities. You defend the people you love with a ferocity that surprises those who only know your warm surface.","The fixed fire of Leo means you do not just start things -- you sustain them. You have the staying power to see your visions through to completion."],
"Scorpio-Sun": ["Your Sun in Scorpio is co-ruled by Mars and Pluto -- the planets of power, transformation, and intensity -- which means your identity is built around depth, truth, and evolution.","You are one of the most psychologically complex signs in the zodiac. There are layers to you that most people never access, and you like it that way.","The shadow of this placement is the desire for control as protection. If you understand everything -- every angle, every motive, every possibility -- nothing can catch you off guard.","You have a remarkable ability to sit with darkness -- your own and others' -- without flinching. This makes you an extraordinary friend in crisis and a profound healer.","Scorpio rules the eighth house of death, rebirth, and shared resources -- which means transformation is not something that happens to you occasionally. It is your fundamental mode of existence.","Your lie detector is legendary. You can read through inauthenticity, manipulation, and performance almost instantly.","The intensity you bring to everything you do is your greatest asset and your greatest challenge. You do not do anything at half power.","Scorpios often appear to have multiple lifetimes within one. The person you are at 40 may be completely unrecognizable from who you were at 20 -- and that is the point."],
"Capricorn-Sun": ["Your Sun in Capricorn is ruled by Saturn -- the planet of discipline, structure, and mastery -- which means your identity is built around achievement, integrity, and the long game.","You have a relationship with time that sets you apart from most signs. You are willing to work for years toward something most people would give up on in months.","The shadow of this placement is defining your worth by your accomplishments. When achievement becomes the condition for self-acceptance, no amount of success is ever quite enough.","You have an instinctive understanding of how systems work and how to navigate them -- which makes you exceptionally effective in almost any professional context.","Capricorn rules the tenth house of career, public reputation, and legacy. These are not just ambitions for you -- they are tied to your deepest sense of identity and meaning.","You often took on adult responsibilities very young, which gave you extraordinary competence but sometimes robbed you of ease.","Your dry humor is one of your most underrated qualities. When you decide to be funny, you are extraordinarily funny -- and most people never see it coming.","Saturn rules Capricorn, and Saturn rewards those who do the work. This means your life genuinely does get better with age."],
"Leo-Rising": ["Leo Rising means the Sun rules your chart -- the only Ascendant with this distinction -- giving you a radiant, warm, and magnetically confident outer presence.","Your first impression is larger than life. There is something about you that people notice immediately -- the way you carry yourself, the warmth you project, the presence you have.","You tend to have a physical quality that draws attention -- strong hair, dramatic features, or simply an energy that takes up space in the best possible way.","The challenge of this Ascendant is that you are always being watched, which can create pressure to perform rather than simply be.","Leo Rising people often find that their life becomes more public than they expected -- career paths involving visibility, leadership, or some form of audience tend to find them.","Your life themes revolve around identity, self-expression, creativity, and the journey from seeking validation to genuinely knowing your own worth.","The Sun ruling your chart means vitality, identity, and creative expression are core to how you show up in the world.","You have a natural gift for leadership that emerges not from ambition but from the simple fact that when you are fully yourself, people naturally follow."],
"Scorpio-Pluto": ["Pluto in Scorpio (born approx. 1983-1995) -- your generation was forged in psychological intensity. You arrived already knowing that transformation is not optional, it is survival.","Your generation broke open the cultural conversation around trauma, mental health, sexuality, and power in ways that no generation before you had the language or courage to do.","You have a collective obsession with truth beneath the surface -- fake, performative, or shallow culture genuinely repels you at an instinctive level.","The wound your generation carries is around trust and betrayal. The gift is an extraordinary collective capacity for radical honesty and deep psychological healing.","You do not fear darkness. You were born into it and you know your way around -- which is why you are often the one others come to when things get real.","Your generation is doing the psychological excavation work that previous generations refused -- and it is genuinely changing what it means to be a conscious human being.","You transform completely and repeatedly throughout your life -- not despite the intensity, but through it. Each version of you is genuinely unrecognizable from the last.","Pluto in Scorpio people often feel they have lived multiple lifetimes within one. That is because, in a meaningful sense, you have."],
"Sagittarius-Jupiter": ["Jupiter in Sagittarius is the planet in its home sign -- this is Jupiter operating at its most abundant and expansive, giving you a genuinely fortunate relationship with growth, opportunity, and belief.","You have a natural magnetism that attracts teachers, mentors, opportunities, and experiences that expand your understanding of the world.","Your optimism is not naivety -- it is a deeply held philosophical position that life is fundamentally meaningful and that things tend to work out. And for you, they often do.","The shadow of this placement is excess -- too much confidence, too many commitments, too grand a vision without the practical steps to match it.","You are at your most alive when you are learning, traveling, teaching, or exploring the edges of what you previously believed was possible.","Your generosity is one of your most defining qualities. You give abundantly -- of your time, your knowledge, your resources, your enthusiasm.","You have a gift for seeing the bigger picture in situations where others are lost in the details, which makes you a valuable strategic thinker and inspiring guide.","Faith -- in people, in ideas, in the universe -- is your most reliable resource. Even when things fall apart, you find a way to believe in what comes next."],
"Capricorn-Saturn": ["Saturn in Capricorn is the planet in its home sign -- meaning your relationship with discipline, structure, and long-term achievement is operating at its most potent.","You have an unusual capacity to delay gratification in service of something more significant. You understand that the best things are built slowly, and you build accordingly.","The shadow of this placement is an internalized authority that is never fully satisfied -- a voice that says more, better, harder regardless of what you have actually accomplished.","You were likely given more responsibility than was appropriate for your age -- which built incredible competence and a quiet loneliness that you may not have fully named.","Your relationship with authority is complex -- you respect it, you can embody it, and you have a finely tuned sense of when it is being abused.","Saturn returns at approximately 29-30 and 58-60 years old, which are often turning points of reckoning and restructuring for this placement in particular.","Your standards are high -- for yourself above all -- which means failure hits you harder than most, and you tend to be harder on yourself than anyone around you ever would be.","The gift of Saturn in Capricorn is that the things you build are real. Not flash, not luck -- genuinely solid, genuinely earned."],
};

const emojis = {
Sun:"☀️", Moon:"🌙", Mercury:"☿", Venus:"♀️", Mars:"♂️",
Jupiter:"♃", Saturn:"♄", Uranus:"🪐", Neptune:"🌊", Pluto:"🔮", Rising:"⬆️",
Aries:"🔥", Taurus:"🌿", Gemini:"✨", Cancer:"🫧", Leo:"👑", Virgo:"🌾",
Libra:"⚖️", Scorpio:"🖤", Sagittarius:"🏹", Capricorn:"⛰️", Aquarius:"⚡", Pisces:"💜",
};

const colors = {
Aries:"#ff6b6b", Taurus:"#a8c97f", Gemini:"#f7c948", Cancer:"#a3c4d8",
Leo:"#ffab40", Virgo:"#8fbc8f", Libra:"#d4a5c9", Scorpio:"#a03060",
Sagittarius:"#e07b39", Capricorn:"#8b7355", Aquarius:"#5bc8d8", Pisces:"#9b8fcc",
};

function getFact(sign, planet) {
const key = sign + "-" + planet;
if (facts[key]) {
const arr = facts[key];
return arr[Math.floor(Math.random() * arr.length)];
}
const generics = [
sign + " " + planet + " gives you a uniquely powerful energy that shapes how you experience this area of life.",
"With " + planet + " in " + sign + ", the qualities of " + sign + " are deeply woven into how you express this planetary energy.",
planet + " in " + sign + " is one of the most revealing placements in understanding your full astrological story.",
"Your " + planet + " in " + sign + " means you approach this area of life with the full force of " + sign + " energy.",
planet + " in " + sign + " shapes you in ways you may recognize immediately or only understand in retrospect.",
];
return generics[Math.floor(Math.random() * generics.length)];
}

const guessClues = {
Aries:["I act before I think -- and somehow it usually works out.","I have been told I am a lot more times than I can count.","I get bored if nothing exciting is happening.","I would rather lead than follow, always.","My temper flares fast -- but I forgive just as quickly."],
Taurus:["People always say my home feels incredibly cozy.","I know exactly what I like -- and I do not apologize for it.","I take my time with decisions, but once I decide, I am decided.","Good food is genuinely one of my love languages.","I am more stubborn than most people realize."],
Gemini:["I can talk to literally anyone about anything.","I have been called two-faced -- I prefer multidimensional.","My brain never shuts off. Ever.","I can see every side of an argument, which makes choosing hard.","I pick up new skills incredibly fast but rarely stick with them long."],
Cancer:["I remember exactly how every important moment felt.","My home is my sanctuary -- I take it very seriously.","I can sense someone's mood the moment I walk in the room.","I tend to nurture everyone around me without being asked.","I hold on to things -- memories, people, feelings -- for a long time."],
Leo:["I light up in front of an audience, even if it is just two people.","I am incredibly loyal -- but I expect the same in return.","I have been told I have a presence that is hard to ignore.","I genuinely love making people feel special and celebrated.","My pride is real -- apologizing does not come naturally."],
Virgo:["I notice the detail everyone else walked right past.","My inner critic is louder than anyone else's voice.","I show love by helping -- practically, specifically, efficiently.","I research things obsessively before making a decision.","I feel physically calmer when my space is organized."],
Libra:["I can see both sides of any argument so clearly it is hard to pick one.","I have a strong physical reaction to things that are ugly or discordant.","Conflict genuinely makes me uncomfortable in my body.","People always come to me to help them navigate their relationships.","I fall in love with the idea of partnership -- deeply."],
Scorpio:["I can tell when someone is lying almost immediately.","I do not do anything halfway -- it is all or nothing.","I have completely reinvented myself at least once, maybe more.","I remember everything. Especially the things that hurt.","People find me magnetic but slightly hard to read -- intentionally."],
Sagittarius:["I genuinely believe things will work out -- and they usually do.","I need freedom more than I need almost anything else.","I say exactly what I think, sometimes before I should.","Travel or learning something new resets me completely.","I have a philosophy for life that I have built entirely from scratch."],
Capricorn:["I have always felt older than my actual age.","I set standards for myself that most people would find exhausting.","My dry humor surprises people who only know my serious side.","I take commitments -- in work and love -- very, very seriously.","Life genuinely gets better for me the older I get."],
Aquarius:["I have always felt slightly outside the group, even when I am in it.","I care about humanity as a whole more than I care about fitting in.","I need space the way other people need air.","I was thinking about things years ago that people are only now discussing.","My emotional needs are genuinely different from most people's."],
Pisces:["I absorb other people's moods without meaning to.","I have a rich inner world that is more real to me than most of reality.","Creative work is not just something I do -- it is how I survive.","I often know things without knowing how I know them.","I love without limits, which is both my gift and my wound."],
};

const celebBySign = {};
celebrities.forEach(c => { if (!celebBySign[c.sign]) celebBySign[c.sign]=[]; celebBySign[c.sign].push(c); });

function CelebrityAvatar({ celeb }) {
return (
<div style={{background:"rgba(255,200,50,0.04)",border:"1px solid rgba(255,200,50,0.2)",borderRadius:16,padding:"24px 20px",textAlign:"center",maxWidth:360,margin:"0 auto"}}>
<div style={{width:80,height:80,borderRadius:"50%",background:"linear-gradient(135deg,rgba(255,200,50,0.15),rgba(168,224,96,0.1))",border:"2px solid rgba(255,200,50,0.4)",margin:"0 auto 12px",display:"flex",alignItems:"center",justifyContent:"center",fontSize:40}}>{celeb.emoji}</div>
<div style={{fontFamily:"'Cinzel',serif",fontWeight:700,fontSize:16,color:"#f5c842",marginBottom:4}}>{celeb.name}</div>
<div style={{fontFamily:"'Cinzel',serif",fontWeight:700,fontSize:11,color:"#a8e060",marginBottom:14}}>Born {celeb.born}</div>
<div style={{display:"flex",gap:6,justifyContent:"center",marginBottom:16,flexWrap:"wrap"}}>
{[["☀️",celeb.sun],["🌙",celeb.moon],["⬆️",celeb.rising]].map(([icon,val])=>(
val&&val!=="Unknown"?(<span key={icon} style={{background:"rgba(255,200,50,0.1)",border:"1px solid rgba(255,200,50,0.3)",borderRadius:6,padding:"3px 9px",fontFamily:"'Cinzel',serif",fontWeight:700,fontSize:9,color:"#f5c842"}}>{icon} {val}</span>):null
))}
</div>
<p style={{fontFamily:"Georgia,serif",fontWeight:700,fontSize:15,color:"#ffffff",lineHeight:1.65,margin:0}}>"{celeb.fact}"</p>
</div>
);
}

function CelebrityConnection() {
const [selectedSign, setSelectedSign] = useState(null);
return (
<div style={{animation:"up .5s ease"}}>
<div style={{textAlign:"center",marginBottom:24}}>
<div style={{fontSize:36,marginBottom:10}}>🌟</div>
<h2 style={{fontFamily:"'Cinzel',serif",fontWeight:900,fontSize:24,color:"#f5c842",margin:"0 0 8px"}}>Celebrity Connection</h2>
<p style={{fontFamily:"Georgia,serif",color:"#a8e060",fontSize:15,margin:0}}>Select a sign to see which celebrity shares that Sun sign.</p>
</div>
<div style={{display:"flex",flexWrap:"wrap",gap:7,justifyContent:"center",marginBottom:28}}>
{signs.map(s=>(
<button key={s} onClick={()=>setSelectedSign(selectedSign===s?null:s)} style={{background:selectedSign===s?("linear-gradient(135deg,"+colors[s]+","+colors[s]+"88)"):"rgba(255,200,50,0.06)",border:"2px solid "+(selectedSign===s?colors[s]:"rgba(255,200,50,0.25)"),color:selectedSign===s?"#0d0a14":"#f0c030",padding:"8px 14px",borderRadius:"100px",fontFamily:"'Cinzel',serif",fontWeight:700,fontSize:10,letterSpacing:".07em",cursor:"pointer",transition:"all 0.22s"}}>{emojis[s]} {s}</button>
))}
</div>
{selectedSign && (
<div style={{animation:"up .4s ease"}}>
<div style={{fontFamily:"'Cinzel',serif",fontWeight:700,fontSize:10,letterSpacing:".18em",color:"#a8e060",marginBottom:16,textAlign:"center"}}>✦ {selectedSign.toUpperCase()} SUN CELEBRITY ✦</div>
{celebBySign[selectedSign]&&celebBySign[selectedSign].length>0?(<CelebrityAvatar celeb={celebBySign[selectedSign][0]} />):(<div style={{textAlign:"center",padding:"32px 20px",background:"rgba(255,200,50,0.04)",border:"1px solid rgba(255,200,50,0.15)",borderRadius:16}}><p style={{fontFamily:"'Cinzel',serif",fontWeight:700,color:"#f5c842",fontSize:16,margin:0}}>More {selectedSign} celebrities coming soon!</p></div>)}
</div>
)}
{!selectedSign&&(<div style={{textAlign:"center",padding:"24px 0",fontFamily:"Georgia,serif",color:"#6a6058",fontSize:15}}>Select a sign above to reveal the stars ✨</div>)}
</div>
);
}

function GuessYourSign() {
const [step, setStep] = useState(0);
const [currentSign, setCurrentSign] = useState(null);
const [clueIndex, setClueIndex] = useState(0);
const [guess, setGuess] = useState(null);
const [score, setScore] = useState({correct:0,total:0});
const [feedback, setFeedback] = useState(null);
const allSigns = Object.keys(guessClues);
const startGame = () => { const s=allSigns[Math.floor(Math.random()*allSigns.length)]; setCurrentSign(s);setClueIndex(0);setGuess(null);setFeedback(null);setStep(1); };
const nextClue = () => { if(clueIndex<guessClues[currentSign].length-1)setClueIndex(i=>i+1); };
const makeGuess = (g) => { setGuess(g); const correct=g===currentSign; setScore(s=>({correct:s.correct+(correct?1:0),total:s.total+1})); setFeedback(correct?"Correct! "+currentSign+" energy is undeniable.":"Not quite -- this was "+currentSign+" "+(emojis[currentSign]||"")); setStep(2); };
if(step===0)return(<div style={{animation:"up .5s ease",textAlign:"center",paddingTop:20}}><div style={{fontSize:48,marginBottom:16}}>🔮</div><h2 style={{fontFamily:"'Cinzel',serif",fontWeight:900,fontSize:26,color:"#f5c842",marginBottom:12}}>Guess Your Sign</h2><p style={{fontFamily:"Georgia,serif",color:"#a8e060",fontSize:16,marginBottom:32}}>Read the clues. Guess the zodiac sign. How well do you know the signs?</p><button className="rb" style={{"--a":"#e8a800"}} onClick={startGame}>✦ START GUESSING</button>{score.total>0&&<p style={{fontFamily:"'Cinzel',serif",fontWeight:700,fontSize:11,color:"#f5c842",marginTop:20}}>Score: {score.correct}/{score.total}</p>}</div>);
if(step===1)return(<div style={{animation:"up .5s ease"}}><div style={{background:"rgba(255,200,50,0.06)",border:"1px solid rgba(255,200,50,0.25)",borderRadius:20,padding:"28px 24px",marginBottom:20,position:"relative",overflow:"hidden"}}><div style={{position:"absolute",top:0,left:0,right:0,height:2,background:"linear-gradient(90deg,transparent,#e8a800,transparent)"}}/><div style={{fontFamily:"'Cinzel',serif",fontWeight:700,fontSize:9,letterSpacing:".2em",color:"#a8e060",marginBottom:16}}>CLUE {clueIndex+1} OF {guessClues[currentSign].length}</div><p style={{fontFamily:"Georgia,serif",fontWeight:700,fontSize:20,color:"#ffffff",lineHeight:1.6,margin:"0 0 20px"}}>"{guessClues[currentSign][clueIndex]}"</p>{clueIndex<guessClues[currentSign].length-1&&(<button onClick={nextClue} style={{background:"none",border:"1px solid rgba(168,224,96,0.3)",color:"#a8e060",padding:"8px 20px",borderRadius:"100px",fontFamily:"'Cinzel',serif",fontWeight:700,fontSize:10,cursor:"pointer",letterSpacing:".1em"}}>NEXT CLUE -&gt;</button>)}</div><div style={{fontFamily:"'Cinzel',serif",fontWeight:700,fontSize:10,letterSpacing:".15em",color:"#f5c842",marginBottom:12}}>YOUR GUESS:</div><div style={{display:"grid",gridTemplateColumns:"repeat(3,1fr)",gap:8}}>{allSigns.map(s=>(<button key={s} className="sb" style={{"--a":colors[s]}} onClick={()=>makeGuess(s)}><div style={{fontSize:14,marginBottom:2}}>{emojis[s]||"★"}</div><div style={{fontSize:9,fontWeight:700}}>{s}</div></button>))}</div></div>);
if(step===2)return(<div style={{animation:"up .5s ease",textAlign:"center"}}><div style={{background:guess===currentSign?"rgba(168,224,96,0.08)":"rgba(255,80,80,0.08)",border:"1px solid "+(guess===currentSign?"rgba(168,224,96,0.4)":"rgba(255,100,100,0.3)"),borderRadius:20,padding:"32px 24px",marginBottom:24}}><div style={{fontSize:40,marginBottom:12}}>{emojis[currentSign]||"★"}</div><p style={{fontFamily:"'Cinzel',serif",fontWeight:700,fontSize:18,color:guess===currentSign?"#a8e060":"#f5c842",margin:"0 0 8px"}}>{feedback}</p><p style={{fontFamily:"'Cinzel',serif",fontWeight:700,fontSize:10,letterSpacing:".15em",color:"#f5c842",margin:0}}>SCORE: {score.correct}/{score.total}</p></div><button className="rb" style={{"--a":"#e8a800"}} onClick={startGame}>✦ PLAY AGAIN</button></div>);
}

export default function AstrologyApp() {
const [mode, setMode] = useState("home");
const [topTab, setTopTab] = useState("facts");
const [selectedSign, setSelectedSign] = useState(null);
const [selectedPlanet, setSelectedPlanet] = useState(null);
const [fact, setFact] = useState(null);
const [animating, setAnimating] = useState(false);
const accent = selectedSign ? colors[selectedSign] : "#e8a800";
const reset = () => { setSelectedSign(null);setSelectedPlanet(null);setFact(null); };

const handleReveal = () => {
if(!selectedSign||!selectedPlanet)return;
setAnimating(true);setFact(null);
setTimeout(()=>{setFact(getFact(selectedSign,selectedPlanet));setAnimating(false);},500);
};

return (
<div style={{minHeight:"100vh",background:"#0d0a14",fontFamily:"Georgia,serif",color:"#ffffff",position:"relative",overflow:"hidden"}}>
<div style={{position:"fixed",inset:0,pointerEvents:"none",zIndex:0}}>
{[...Array(70)].map((_,i)=>(<div key={i} style={{position:"absolute",width:Math.random()*2.5+0.4+"px",height:Math.random()*2.5+0.4+"px",borderRadius:"50%",background:i%7===0?("rgba(168,224,96,"+(Math.random()*0.5+0.2)+")"): ("rgba(255,200,50,"+(Math.random()*0.5+0.15)+")"),left:Math.random()*100+"%",top:Math.random()*100+"%",animation:"tw "+(Math.random()*3+2)+"s ease-in-out infinite",animationDelay:Math.random()*4+"s"}}/>))}
</div>
<style>{`@import url('https://fonts.googleapis.com/css2?family=Cinzel:wght@400;700;900&display=swap'); @keyframes tw{0%,100%{opacity:0.2}50%{opacity:1}} @keyframes up{from{opacity:0;transform:translateY(18px)}to{opacity:1;transform:translateY(0)}} @keyframes sh{0%{background-position:200% center}100%{background-position:-200% center}} @keyframes gl{0%,100%{box-shadow:0 0 18px 3px rgba(232,168,0,0.3)}50%{box-shadow:0 0 40px 10px rgba(232,168,0,0.6)}} @keyframes pu{0%,100%{opacity:0.4}50%{opacity:1}} .sb{background:rgba(255,200,50,0.06);border:1px solid rgba(255,200,50,0.2);color:#f0c030;padding:9px 12px;border-radius:8px;cursor:pointer;font-family:'Cinzel',serif;font-size:10px;letter-spacing:.07em;font-weight:700;transition:all .22s;text-align:center} .sb:hover,.sb.sel{background:rgba(255,200,50,0.15);color:#f5c842;border-color:var(--a);transform:translateY(-2px)} .pb{background:rgba(255,200,50,0.05);border:1px solid rgba(255,200,50,0.18);color:#f0c030;padding:9px 18px;border-radius:100px;cursor:pointer;font-family:'Cinzel',serif;font-size:11px;letter-spacing:.09em;font-weight:700;transition:all .22s} .pb:hover,.pb.sel{background:rgba(255,200,50,0.15);color:#f5c842;border-color:var(--a)} .rb{background:linear-gradient(135deg,var(--a),#8a6000);color:#0d0a14;border:none;padding:14px 38px;border-radius:100px;font-family:'Cinzel',serif;font-size:13px;letter-spacing:.14em;font-weight:900;cursor:pointer;transition:all .3s;animation:gl 3s ease-in-out infinite} .rb:hover{transform:scale(1.04);filter:brightness(1.12)} .fc{animation:up .65s ease forwards;background:linear-gradient(135deg,rgba(255,200,50,0.08),rgba(0,0,0,0.3));border:1px solid rgba(255,200,50,0.3);border-radius:20px;padding:30px 34px;position:relative;overflow:hidden} .fc::before{content:'';position:absolute;top:0;left:0;right:0;height:2px;background:linear-gradient(90deg,transparent,var(--a),transparent)} .bk{background:none;border:none;color:#5a5048;cursor:pointer;font-family:'Cinzel',serif;font-size:10px;letter-spacing:.13em;font-weight:700;display:flex;align-items:center;gap:6px;margin-bottom:28px} .bk:hover{color:#a8e060} .gn{display:inline-block;background:rgba(168,224,96,0.08);border:1px solid rgba(168,224,96,0.3);border-radius:100px;padding:2px 10px;font-family:'Cinzel',serif;font-size:9px;letter-spacing:.08em;color:#a8e060;margin-left:7px;font-weight:700}`}</style>

  <div style={{position:"relative",zIndex:1,maxWidth:700,margin:"0 auto",padding:"20px 18px 80px"}}>
    <div style={{display:"flex",gap:8,justifyContent:"center",marginBottom:24,flexWrap:"wrap"}}>
      {[{label:"✦ Fun Facts",key:"facts"},{label:"🌟 Celebrity",key:"celebrity"},{label:"🔮 Guess Your Sign",key:"guess"}].map(tab=>(
        <button key={tab.key} onClick={()=>{setTopTab(tab.key);setMode("home");reset();}} style={{background:topTab===tab.key?"linear-gradient(135deg,#e8a800,#8a6000)":"rgba(255,200,50,0.08)",border:"2px solid "+(topTab===tab.key?"#e8a800":"rgba(255,200,50,0.3)"),color:topTab===tab.key?"#0d0a14":"#f5c842",padding:"11px 18px",borderRadius:"100px",fontFamily:"'Cinzel',serif",fontWeight:900,fontSize:11,letterSpacing:".09em",cursor:"pointer",transition:"all 0.25s",boxShadow:topTab===tab.key?"0 0 16px 4px rgba(232,168,0,0.3)":"none"}}>{tab.label}</button>
      ))}
    </div>

    {topTab==="celebrity" && <CelebrityConnection />}
    {topTab==="guess" && <GuessYourSign />}

    {topTab==="facts" && <>
      <div style={{textAlign:"center",marginBottom:24}}>
        <div style={{fontSize:11,fontFamily:"'Cinzel',serif",fontWeight:700,letterSpacing:".3em",color:"#a8e060",marginBottom:12}}>✦ CELESTIAL INSIGHTS ✦</div>
        <h1 style={{fontFamily:"'Cinzel',serif",fontWeight:900,fontSize:"clamp(28px,6vw,52px)",lineHeight:1.05,margin:"0 0 10px",background:"linear-gradient(135deg,#f5c842,#e8a800,#f5c842)",backgroundSize:"200% auto",WebkitBackgroundClip:"text",WebkitTextFillColor:"transparent",backgroundClip:"text",animation:"sh 4s linear infinite"}}>
          Your Cosmic Fun Facts
        </h1>
        <p style={{color:"#a8e060",fontFamily:"'Cinzel',serif",fontWeight:700,fontSize:13,margin:0,letterSpacing:".05em"}}>Discover what the stars reveal about you</p>
      </div>

      {mode==="home" && (
        <div style={{animation:"up .5s ease",textAlign:"center",paddingTop:20}}>
          <div style={{fontSize:48,marginBottom:20}}>🌙</div>
          <div style={{fontFamily:"Georgia,serif",fontSize:17,color:"#7a6e62",marginBottom:36}}>Choose a sign and a planet to discover your cosmic fun fact.</div>
          <button className="rb" style={{"--a":"#e8a800"}} onClick={()=>setMode("single")}>✦ EXPLORE YOUR PLACEMENTS</button>
        </div>
      )}

      {mode==="single" && (
        <div style={{animation:"up .45s ease"}}>
          <button className="bk" onClick={()=>{setMode("home");reset();}}>← BACK</button>
          <div style={{marginBottom:30}}>
            <div style={{fontFamily:"'Cinzel',serif",fontWeight:700,fontSize:10,letterSpacing:".18em",color:accent,marginBottom:12,display:"flex",alignItems:"center",gap:9}}>
              <span style={{width:19,height:19,borderRadius:"50%",background:accent,display:"inline-flex",alignItems:"center",justifyContent:"center",fontSize:9,color:"#0d0a14",fontWeight:700,flexShrink:0}}>1</span>
              SELECT YOUR SIGN
            </div>
            <div style={{display:"grid",gridTemplateColumns:"repeat(4,1fr)",gap:7}}>
              {signs.map(s=>(<button key={s} className={"sb"+(selectedSign===s?" sel":"")} style={{"--a":colors[s]}} onClick={()=>{setSelectedSign(s);setFact(null);}}><div style={{fontSize:16,marginBottom:3}}>{emojis[s]}</div><div style={{fontSize:9}}>{s}</div></button>))}
            </div>
          </div>

          {selectedSign && (
            <div style={{marginBottom:30,animation:"up .4s ease"}}>
              <div style={{fontFamily:"'Cinzel',serif",fontWeight:700,fontSize:10,letterSpacing:".18em",color:accent,marginBottom:12,display:"flex",alignItems:"center",gap:9}}>
                <span style={{width:19,height:19,borderRadius:"50%",background:accent,display:"inline-flex",alignItems:"center",justifyContent:"center",fontSize:9,color:"#0d0a14",fontWeight:700,flexShrink:0}}>2</span>
                SELECT YOUR PLANET
              </div>
              <div style={{display:"flex",flexWrap:"wrap",gap:7}}>
                {planets.map(p=>(<button key={p} className={"pb"+(selectedPlanet===p?" sel":"")} style={{"--a":accent}} onClick={()=>{setSelectedPlanet(p);setFact(null);}}>{emojis[p]} {p}</button>))}
              </div>
            </div>
          )}

          {selectedSign && selectedPlanet && (
            <div style={{textAlign:"center",marginBottom:28,animation:"up .4s ease"}}>
              <div style={{fontFamily:"'Cinzel',serif",fontWeight:700,fontSize:17,color:"#f5c842",marginBottom:6}}>{emojis[selectedPlanet]} {selectedPlanet} in {selectedSign} {emojis[selectedSign]}</div>
              {OUTER.includes(selectedPlanet) && generationDates[selectedPlanet] && generationDates[selectedPlanet][selectedSign] && (
                <div style={{fontFamily:"'Cinzel',serif",fontWeight:700,fontSize:9,color:"#a8e060",letterSpacing:".09em",marginBottom:18}}>Born approx. {generationDates[selectedPlanet][selectedSign]}</div>
              )}
              <button className="rb" style={{"--a":accent}} onClick={handleReveal}>{fact?"✦ REVEAL ANOTHER FACT":"✦ REVEAL MY COSMIC FACT"}</button>
            </div>
          )}

          {animating && <div style={{textAlign:"center",padding:28,color:accent,fontSize:26,animation:"pu .5s ease infinite"}}>✦</div>}

          {fact && !animating && (
            <div className="fc" style={{"--a":accent}}>
              <div style={{fontSize:28,marginBottom:14,textAlign:"center"}}>{emojis[selectedSign]}{emojis[selectedPlanet]}</div>
              <p style={{fontFamily:"Georgia,serif",fontWeight:700,fontSize:"clamp(15px,3vw,20px)",lineHeight:1.78,margin:"0 0 22px",color:"#f5c842",textAlign:"center"}}>"{fact}"</p>
              <div style={{textAlign:"center"}}><span style={{fontFamily:"'Cinzel',serif",fontWeight:700,fontSize:9,letterSpacing:".18em",color:accent,opacity:.8}}>✦ {selectedPlanet.toUpperCase()} IN {selectedSign.toUpperCase()} ✦</span></div>
            </div>
          )}

          {(selectedSign||selectedPlanet) && (
            <div style={{textAlign:"center",marginTop:24}}>
              <button onClick={reset} style={{background:"none",border:"none",color:"#504840",cursor:"pointer",fontFamily:"'Cinzel',serif",fontWeight:700,fontSize:9,letterSpacing:".13em"}}>← START OVER</button>
            </div>
          )}
        </div>
      )}
    </>}

    <div style={{textAlign:"center",marginTop:60,paddingTop:24,borderTop:"1px solid rgba(255,200,50,0.08)"}}>
      <p style={{fontFamily:"'Cinzel',serif",fontWeight:700,fontSize:11,color:"#3a3430",margin:0,letterSpacing:".1em"}}>
        powered by <span style={{color:"#a8e060"}}>Ayssia</span>
      </p>
    </div>
  </div>
</div>
);
}
